### ISSUE TITLE
[Enhancement] Adding a Login/Signup Page

### ISSUE THREAD

**Issue by thatguywhocode** [sayandippaul/IRIS-Smart-Tutor#25]
The current website does not have any login page. By adding a login page, the website will look more authentic.

**Comment by thatguywhocode** [comment]
Hey @sayandippaul ,please Assign me this task under JWOC.

**Comment by Syed0206** [comment]
@sayandippaul please Assign me this task under JWOC.

**Comment by vishal2005025** [comment]
Please assign it to me under JWOC'2024.

**Comment by sayandippaul** [comment]
assigned

**Comment by thatguywhocode** [comment]
Hey @sayandippaul  , I created pr under JWOC. Please assign JWOC tag and difficulty level too. Thanks
