### ISSUE TITLE
Make Contact us form functional

### ISSUE THREAD

**Issue by PranavBarthwal** [sayandippaul/IRIS-Smart-Tutor#44]
Currently the contact us form is not working and throws error on submitting a message. Ill make the contact us form functional.
please assign this issue to me under JWoC'24
![image](https://github.com/sayandippaul/IRIS-Smart-Tutor/assets/110532770/f1a8dc53-1dda-491b-9164-997812d735bc)
![Screenshot (94)](https://github.com/sayandippaul/IRIS-Smart-Tutor/assets/110532770/9aafa604-6f8e-4dd9-b9b9-b6f1d2bb9f1f)

**Comment by sayandippaul** [comment]
Assigned

**Comment by PranavBarthwal** [comment]
> Assigned

Please drop the email which you want to be connected with the form
