### ISSUE TITLE
Footer color mis match 

### ISSUE THREAD

**Issue by AftabMankapure** [sayandippaul/IRIS-Smart-Tutor#47]
**### Add same color to footer and navbar to look good and classic** 

**Current footer style**
![ofo](https://github.com/sayandippaul/IRIS-Smart-Tutor/assets/125949765/9042460f-1064-4a4e-880b-ce6929de2462)

**New footer style**
![nfo](https://github.com/sayandippaul/IRIS-Smart-Tutor/assets/125949765/69cf4691-f231-4600-b81f-1d2120c3d190)

Assign me under JWOC

**Comment by sayandippaul** [comment]
Assignied

**Comment by AftabMankapure** [comment]
PLS Add **JWOC** and **HARD** label
