### ISSUE TITLE
In the quiz section

### ISSUE THREAD

**Issue by rajlakshmi18704** [sayandippaul/IRIS-Smart-Tutor#5]
On not  selecting any courses  a pop is appearing whose language is not appropriate  which needs to be change.

**Comment by rajlakshmi18704** [comment]
I would like to work on this issue under JWOC

**Comment by sayandippaul** [comment]
Assigning

**Comment by vishapraj** [comment]
I want to work on this issue , please assign me.

**Comment by sayandippaul** [comment]
assigning

**Comment by vishapraj** [comment]
Is it closed or I can work on this issue?

**Comment by vishal2005025** [comment]
please assign it to me under JWOC'2024.
